name: RecipeRoomCI
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  rspec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.6'

      - name: Install dependencies
        run: |
          cd api
          bundle install


      - name: Run RSpec
        run: |
          cd api
          bundle exec rspec
