name: RecipeRoomCI
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  rspec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.6'

      - name: Install dependencies
        run: |
          cd api
          bundle install --jobs 4 --retry 3

      - name: Install RSpec
        run: |
          cd api
          gem install rspec

      - name: Build React frontend
        uses: actions/setup-node@v2
        with:
          node-version: '14'
        run: |
          cd client
          npm install
          npm run build
          npm pack
          mv recipe-room-client-*.tgz ../api/

      - name: Bundle dependencies
        uses: jvandemo/github-action-bundle-dependencies@v1
        with:
          directory: api
          exclude: |
            *.lock
            *.log
            *.tgz

      - name: Run RSpec
        run: |
          cd api
          bundle exec rspec
